name: Deriv Pro Trader

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Bot
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          DERIV_PAT_DEMO: ${{ secrets.DERIV_PAT_DEMO }}
          DERIV_APP_ID: ${{ vars.DERIV_APP_ID || '1089' }}
        run: python main.py
